title: αlpha.zero
email: dotzeroalpha@gmail.com
description: >-
baseurl: 
url: https://alphazero-official.github.io
twitter_username: alphazeroOFF
youtube_username: alphazeroOfficial
github_username:  alphazero-official
github_repo: "alphazero-official/alphazero-official.github.io"
discord_link: 2xqnQ66bCQ
bandcamp_url: "1oolm"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-seo-tag
  - jemoji

collections:
  about:
    output: true
    permalink: /:collection/:name
  credits:
    output: true
    permalink: /:name

logo: "/assets/image/AZ2022.png"

disqus:
  shortname: alphazero-1

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/